Repository neelshah2409/Bot-Collection, pull requests merged in 2022-02, with the labels that each got.

#17 messenger bot
  messenger_module.py
Labels: easy, JWOC

#25 Make a twitter bot
  .gitignore
  TwitterBots/README.md
  TwitterBots/config.py
  TwitterBots/keys.py
  TwitterBots/retweet.py
Labels: Moderate, JWOC

#28 added new features to the covid telegram bot
  covid_bot/.env
  covid_bot/README.md
  covid_bot/covid_telegram_bot.py
  covid_bot/requirements.txt
  covid_bot/ss1.png
  covid_telegram_bot.py
Labels: easy, JWOC

#31 Made a discord weather bot
  Discord Weather Bot/README.md
  Discord Weather Bot/__pycache__/weather.cpython-39.pyc
  Discord Weather Bot/img/preview.png
  Discord Weather Bot/img/weather icon.png
  Discord Weather Bot/main.py
  Discord Weather Bot/weather.py
Labels: Moderate, JWOC

#29 Wotd whatsapp bot
  WOTD_Bot/README.md
  WOTD_Bot/requirements.txt
  WOTD_Bot/wotd_bot.py
Labels: JWOC, Medium
